name: Example Workflow
on: [push]

jobs:
  example-job:
    name: An example job
    runs-on: ubuntu-latest     
    steps:
      - name: Echo MY_VERSION step 1
        run: echo $MY_VERSION
        env:
          MY_VERSION: 1.0.{{ github.run_number }}

      - name: Echo MY_VERSION step 1
        run: echo $MY_VERSION
        env:
          MY_VERSION: 1.0.{{ github.run_number }}
